name: Tests

on:
  push:
    branches: [main]
  pull_request:
    # Check all PR

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            python-version: "3.8"
          - os: ubuntu-22.04
            python-version: "3.11"
          - os: macos-11
            python-version: "3.8"
          - os: macos-11
            python-version: "3.11"
          - os: windows-2019
            python-version: "3.8"
          - os: windows-2019
            python-version: "3.11"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install tox

    - name: run Python tests
      run: tox -e tests
